# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
  #    param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  routing_loader: false
  format_listener:
    rules:
      - {
          path: ^/api,
          prefer_extension: true,
          fallback_format: json,
          priorities: [json, html],
        }
      - {
          path: ^/auth,
          prefer_extension: false,
          fallback_format: json,
          priorities: [json],
        }
      - {
          path: ^/connect/google,
          prefer_extension: false,
          fallback_format: json,
          priorities: [json],
        }
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
