lexik_jwt_authentication:
  private_key_path: "%env(resolve:JWT_PRIVATE_KEY)%"
  public_key_path: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 20368000
  user_identity_field: email
