# config/packages/prod/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
  private_key: "%env(JWT_PRIVATE_KEY)%"
  public_key: "%env(JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 20368000
  user_identity_field: email
